#  飞书
APP_ID: cli_axxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx
# 请确保和飞书应用管理平台中的设置一致 
BOT_NAME: chatGpt
# openAI
OPENAI_KEY: 
- sk-xxx
- sk-xxx
- sk-xxx
- sk-xxx
- sk-xxx
- sk-xxx
- sk-xxx
- sk-xxx
- sk-xxx
- sk-xxx

# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: /cert.pem
KEY_FILE: /key.pem

